common:
  model: deepseek-ai/DeepSeek-R1-0528-Qwen3-8B
  tensor_parallel_size: 1
  model_type: deepseek
  max_tokens: 64000
  warmup_traces: 16
  total_budget: 256
  confidence_percentile: 90
  window_size: 2048
  sampling:
    temperature: 0.6
    top_p: 0.95
    top_k: 0
  vllm:
    enable_prefix_caching: true
    trust_remote_code: true

online:
  dataset: ./data/brumo_2025.jsonl
  output_dir: outputs/deepseek_r1_qwen3_8b/online

baseline:
  dataset: ./data/brumo_2025.jsonl
  output_dir: outputs/deepseek_r1_qwen3_8b/baseline
  budget: 256

offline:
  model: deepseek-ai/DeepSeek-R1-0528-Qwen3-8B
  model_type: deepseek
  tensor_parallel_size: 1
  dataset: ./data/aime25.jsonl
  output_dir: outputs/deepseek_r1_qwen3_8b/offline
  budget: 512
  reasoning_effort: high
  max_tokens: 64000
  sampling:
    temperature: 0.6
    top_p: 0.95
    top_k: 0
